trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - src/SpectabisService

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: '$(Configuration)'

steps:

- task: Bash@3
  displayName: 'Initialize pipeline'
  inputs:
    targetType: 'inline'
    script: |
      echo "##vso[task.setvariable variable=CommithHash]$(git log --pretty=format:'%h' -n 1)"
      mkdir $ARTIFACTSFOLDER

- task: UseDotNet@2
  displayName: 'Install Dotnet SDK'
  inputs:
    packageType: 'sdk'
    version: '3.1.101'

- task: PowerShell@2
  displayName: 'Insert service secrets'
  inputs:
    filePath: 'Scripts/InsertSecretsInSource.ps1'
    arguments: 'src/ServiceClient/Helpers/ServiceCredentialsHelper.cs'
  env:
    SERVICE_API_KEY: $(SERVICE_API_KEY)
    TELEMETRY_KEY: $(TELEMETRY_KEY)

- script: dotnet publish -c $CONFIGURATION -r linux-x64
  displayName: 'Build for linux-x64'

- script: dotnet publish -c $CONFIGURATION -r osx-x64
  displayName: 'Build for osx-x64'

- script: dotnet publish -c $CONFIGURATION -r win-x64
  displayName: 'Build for win-x64'

- task: Bash@3
  displayName: 'Copy resources'
  inputs:
    targetType: 'inline'
    script: |
      cp src/SpectabisNext/Resources src/SpectabisNext/bin/$CONFIGURATION/$SDKRELEASEFOLDER/linux-x64/publish/ -r
      cp src/SpectabisNext/Resources src/SpectabisNext/bin/$CONFIGURATION/$SDKRELEASEFOLDER/osx-x64/publish/ -r
      cp src/SpectabisNext/Resources src/SpectabisNext/bin/$CONFIGURATION/$SDKRELEASEFOLDER/win-x64/publish/ -r

- task: Bash@3
  displayName: 'Package build artifacts'
  inputs:
    targetType: 'inline'
    script: |
      tar -cvzf $ARTIFACTSFOLDER/spectabis-linux-$(Build.SourceVersion).tar.gz src/SpectabisNext/bin/$CONFIGURATION/$SDKRELEASEFOLDER/linux-x64/publish
      tar -cvzf $ARTIFACTSFOLDER/spectabis-osx-$(Build.SourceVersion).tar.gz src/SpectabisNext/bin/$CONFIGURATION/$SDKRELEASEFOLDER/osx-x64/publish
      tar -cvzf $ARTIFACTSFOLDER/spectabis-win-$(Build.SourceVersion).tar.gz src/SpectabisNext/bin/$CONFIGURATION/$SDKRELEASEFOLDER/win-x64/publish

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/$(ArtifactsFolder)/spectabis-linux-$(Build.SourceVersion).tar.gz'
    artifact: 'Spectabis-Linux'
    publishLocation: 'pipeline'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/$(ArtifactsFolder)/spectabis-osx-$(Build.SourceVersion).tar.gz'
    artifact: 'Spectabis-OSX'
    publishLocation: 'pipeline'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/$(ArtifactsFolder)/spectabis-win-$(Build.SourceVersion).tar.gz'
    artifact: 'Spectabis-Windows'
    publishLocation: 'pipeline'