name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: .NET Core CLI
      uses: baruchiro/github-actions@0.0.1
    - name: Build for all platforms
      run: |
        dotnet publish -c $CONFIGURATION -r linux-x64
        dotnet publish -c $CONFIGURATION -r win-x64
        dotnet publish -c $CONFIGURATION -r osx-x64
    - name: Package Build Artifacts
      run: |
        mkdir artifacts
        tar -cvzf artifacts/spectabis-linux-$(GITHUB_SHA).tar.gz src/SpectabisNext/bin/Release/$SDKRELEASEFOLDER/linux-x64/publish
        tar -cvzf artifacts/spectabis-win-$(GITHUB_SHA).tar.gz src/SpectabisNext/bin/Release/$SDKRELEASEFOLDER/win-x64/publish
        tar -cvzf artifacts/spectabis-osx-$(GITHUB_SHA).tar.gz src/SpectabisNext/bin/Release/$SDKRELEASEFOLDER/osx-x64/publish
    - name: Publish Linux Artifact
      uses: actions/upload-artifact@v1
      with:
        name: linux-x64
        path: artifacts/spectabis-linux-$(GITHUB_SHA).tar.gz
    - name: Publish Windows Artifact
      uses: actions/upload-artifact@v1
      with:
        name: windows-x64
        path: artifacts/spectabis-win-$(GITHUB_SHA).tar.gz
    - name: Publish Osx Artifact
      uses: actions/upload-artifact@v1
      with:
        name: osx-x64
        path: artifacts/spectabis-osx-$(GITHUB_SHA).tar.gz
